-- MySQL Script generated by MySQL Workbench
-- Wed Aug 29 14:01:45 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`type` (
  `id_type` INT NULL,
  `type` VARCHAR(45) NULL,
  PRIMARY KEY (`id_type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`societes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`societes` (
  `id_society` INT NULL AUTO_INCREMENT,
  `society_name` VARCHAR(45) NULL,
  `society_adress` VARCHAR(200) NULL,
  `country` VARCHAR(45) NULL,
  `TVA` INT NULL,
  `society_phone` INT NULL,
  `type_id_type` INT NOT NULL,
  PRIMARY KEY (`id_society`),
  INDEX `fk_societes_type_idx` (`type_id_type` ASC) VISIBLE,
  CONSTRAINT `fk_societes_type`
    FOREIGN KEY (`type_id_type`)
    REFERENCES `mydb`.`type` (`id_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`personnes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`personnes` (
  `id_personnes` INT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  `phone_number` INT NULL,
  `email` VARCHAR(45) NULL,
  `societes_id_society` INT NOT NULL,
  PRIMARY KEY (`id_personnes`),
  INDEX `fk_personnes_societes1_idx` (`societes_id_society` ASC) VISIBLE,
  CONSTRAINT `fk_personnes_societes1`
    FOREIGN KEY (`societes_id_society`)
    REFERENCES `mydb`.`societes` (`id_society`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`factures`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`factures` (
  `id_facture` INT NULL AUTO_INCREMENT,
  `facture_number` VARCHAR(45) NULL,
  `facture_date` DATETIME NULL,
  `prestation` VARCHAR(45) NULL,
  `societes_id_society` INT NOT NULL,
  `personnes_id_personnes` INT NOT NULL,
  PRIMARY KEY (`id_facture`),
  INDEX `fk_factures_societes1_idx` (`societes_id_society` ASC) VISIBLE,
  INDEX `fk_factures_personnes1_idx` (`personnes_id_personnes` ASC) VISIBLE,
  CONSTRAINT `fk_factures_societes1`
    FOREIGN KEY (`societes_id_society`)
    REFERENCES `mydb`.`societes` (`id_society`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_factures_personnes1`
    FOREIGN KEY (`personnes_id_personnes`)
    REFERENCES `mydb`.`personnes` (`id_personnes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`category` (
  `category_id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`category_id`));

USE `mydb` ;

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `mydb`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`view1`;
USE `mydb`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
